[tools]
bat = "latest"
docker-cli = "latest"
fzf = "latest"
go = "1.25.3"
k9s = "latest"
krew = "latest"
kubectl = "latest"
kubelogin = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
terraform = "latest"
tilt = "latest"
vault = "latest"
xh = "latest"
yq = "latest"
